#!/usr/bin/env python3
import sys
from collections import defaultdict

counts = defaultdict(int)
for line in sys.stdin:
    k, v = line.rstrip('\n').split('\t', 1)
    counts[k] += int(v)

for k, v in counts.items():
    print(f"{k}\t{v}")

